#!/bin/sh

MY_DIR=$(dirname "$0")
TARGET="${DOCKER_WS_TARGET:-/.ws}"
TARGET_DIR=$(dirname "$TARGET")
mkdir -p "$TARGET_DIR"
cp -R "$MY_DIR" "$TARGET"

TOOLS_SOURCE="$DOCKER_WS_TOOLS_SOURCE"
if [ -e "$TOOLS_SOURCE" ]; then
  TOOLS_TARGET="${DOCKER_WS_TOOLS_TARGET:-/.wstools}"
  TOOLS_TARGET_DIR=$(dirname "$TOOLS_TARGET")
  mkdir -p "$TOOLS_TARGET_DIR"
  cp -R "$TOOLS_SOURCE" "$TOOLS_TARGET"
fi

# Trap signals for fast shutdown
trap 'exit 130' INT
trap 'exit 143' TERM

"$TARGET_DIR/sync" & wait $!
