#!/bin/sh

# Determine source directory
SOURCE="${DOCKER_WS_SYNC_SOURCE:-/.src}"
if [ ! -e "$SOURCE" ]; then
  # No source to sync from; exit
  exit 1
fi

# Determine target directory
TARGET="${DOCKER_WS_SYNC_TARGET:-$(pwd)}"
if [ ! -e "$TARGET" ]; then
  # No target to sync to; exit
  exit 1
fi

# Determine log file
LOG="${DOCKER_WS_SYNC_LOG:-/.wssynclog}"

# Change to source directory
cd "$SOURCE"

# Run watch and respond to changes
MY_DIR=$(dirname "$0")
"$MY_DIR/watch" | while read action file; do
  DELETE=$(echo "$action" | grep -)
  if [ -n "$DELETE" ]; then
    # Directory or file was removed
    echo rm -rf \"$TARGET/$file\" >> "$LOG"
    rm -rf "$TARGET/$file"
  elif [ -d "$file" ]; then
    # Directory was updated or added
    echo mkdir -p \"$TARGET/$file\" >> "$LOG"
    mkdir -p "$TARGET/$file"
  else
    # File was updated or added
    DIR=$(dirname "$file")
    echo mkdir -p \"$TARGET/$DIR\" >> "$LOG"
    mkdir -p "$TARGET/$DIR"
    echo cp \"$file\" \"$TARGET/$file\" >> "$LOG"
    cp "$file" "$TARGET/$file"
  fi
done
